#cloud-config
merge_how:
 - name: list
   settings: [append]
 - name: dict
   settings: [recurse_array]

write_files:
  - owner: root:root
    path: /etc/systemd/system/grafana.service
    permissions: '0644'
    content: |
      [Unit]
      Description=Grafana Monitoring
      After=docker.service
      Requires=docker.service

      [Service]
      Restart=always
      ExecStart=/usr/bin/docker run --rm \
          -p 3000:3000 \
          --net spotlight \
          -v /etc/grafana:/etc/grafana \
          -v /var/lib/grafana:/var/lib/grafana \
          --name grafana \
          --label "traefik.enable=true" \
          --label "traefik.http.routers.grafana.rule=Host(`${grafana_domain}`)" \
          --label "traefik.http.routers.grafana.entrypoints=websecure" \
          --label "traefik.http.routers.grafana.tls=true" \
          --label "traefik.http.routers.grafana.tls.certresolver=acme" \
          grafana/grafana:11.5.0

      [Install]
      WantedBy=multi-user.target

runcmd:
  - mkdir -p /var/lib/grafana
  - chown -R 472:472 /var/lib/grafana

  # Launch grafana
  - systemctl daemon-reload
  - systemctl enable grafana
  - systemctl start grafana
