#cloud-config
merge_how:
 - name: list
   settings: [append]
 - name: dict
   settings: [recurse_array]

write_files:
  - owner: root:root
    path: /etc/systemd/system/node-exporter.service
    permissions: '0644'
    content: |
      [Unit]
      Description=Prometheus Node Metrics Exporter

      [Service]
      Restart=always
      ExecStart=/usr/bin/docker run --rm \
          --name node-exporter \
          --net spotlight \
          --pid="host" \
          --label "traefik.enable=true" \
          --label "traefik.http.routers.node_exporter.rule=Host(`${grafana_domain}`) && Path(`/metrics/node`)" \
          --label "traefik.http.routers.node_exporter.entrypoints=websecure" \
          --label "traefik.http.routers.node_exporter.tls=true" \
          --label "traefik.http.routers.node_exporter.tls.certresolver=acme" \
          --label "traefik.http.services.node_exporter.loadbalancer.server.port=9100" \
          -v "/:/host:ro,rslave" \
          quay.io/prometheus/node-exporter:latest \
                --path.rootfs=/host \
                --web.telemetry-path="/metrics/node" \
                --collector.filesystem.ignored-mount-points="^/(sys|proc|dev|run|var/lib/docker.*|mnt/HC_.*)($|/)" \
                --collector.netdev.device-exclude="^(docker[0-9]|vboxnet[0-9]|br-.+|veth.+)$"

      [Install]
      WantedBy=multi-user.target

runcmd:
  # Launch node-exporter
  - systemctl daemon-reload
  - systemctl enable node-exporter
  - systemctl start node-exporter
