#cloud-config
merge_how:
 - name: list
   settings: [append]
 - name: dict
   settings: [recurse_array]

mounts:
 - [ /dev/sdb, /var/lib/prometheus, "ext4", "defaults,nofail,discard,noatime", "0", "0" ]

write_files:
  - owner: root:root
    path: /etc/systemd/system/prometheus.service
    permissions: '0644'
    content: |
      [Unit]
      Description=Prometheus Monitoring
      After=docker.service
      Requires=docker.service

      [Service]
      Restart=always
      ExecStart=/usr/bin/docker run --rm \
          -p 9090:9090 \
          --net spotlight \
          -v /etc/prometheus:/etc/prometheus \
          -v /var/lib/prometheus/data:/data \
          --name %N \
          prom/prometheus:v2.55.1 \
          --config.file=/etc/prometheus/prometheus.yaml \
          --storage.tsdb.path=/data \
          --storage.tsdb.retention.size=60GB \
          --web.enable-lifecycle \
          --web.enable-admin-api \
          --enable-feature=memory-snapshot-on-shutdown

      [Install]
      WantedBy=multi-user.target

runcmd:
  # Create storage directory
  - mount -a
  - mkdir -p /var/lib/prometheus/data
  - mkdir -p /var/lib/prometheus/acme
  - chown -R nobody:nogroup /var/lib/prometheus/data

  # Launch prometheus
  - systemctl daemon-reload
  - systemctl enable prometheus
  - systemctl start prometheus
