#cloud-config
merge_how:
 - name: list
   settings: [append]
 - name: dict
   settings: [recurse_array]

runcmd:
  - sleep 5
%{ for service in services ~}
  - echo -n "Testing ${service} ... "
  - systemctl is-active --wait ${service}
%{ endfor ~}
